spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teatro_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
